### PR TITLE
Fixing minor Bug and adding commandlookup Subcommand

### PR DESCRIPTION
**Pull request by oxolotel**
I hope i didnt break anything... First ever PR to any public repo.

I fixed a small Bug in /athena stop <event>. If you listened to more than one Event and did /athena stop <event> you whouldnt have been able to stop listening to any other event.

I also added a subcommand to lookup the plugin of any Command registered on the server. (/athena lookup <command>)

### CODE REVIEW

**Review by Thatsmusic99 — CHANGES_REQUESTED** [review]
All looks good here, and can confirm the issue the PR aims to fix has been fixed. However, a couple of nitpicks:

1. `/athena lookup` returns "command does not exist" when checking an inbuilt command (e.g. from Paper, Bukkit, or even Minecraft itself):
image

You can probably address this using CommandMap#getCommand(String), and checking if the command is an instance of BukkitCommand (see direct known subclasses, you shouldn't need to worry about the other two: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/Command.html)

In addition, the tab complete returns *all* commands, e.g. `essentials:tpa` - which I think is self-explanatory in terms of what plugin is controlling it, maybe we can remove commands from the tab completion that contain a colon to reduce the noise.

2. I don't see any change in your code that could cause this (worst case scenario this PR gets blocked by #17) but did the plugin suddenly start accusing everything of changing? Like this, for example:

image

If not I can take a look into that.

But otherwise, you didn't break anything awfully, and is very good for a first time PR, definitely go ahead and start contributing to other large-scale projects as well when you get the opportunity and show 'em what you've got!

**Comment by Thatsmusic99** [comment]
Oh dear, don't worry about the second part, it looks like it's happening on #17 as well so that's a me problem

**Comment by oxolotel** [comment]
Remaining problems with the lookup command should be fixed now.

**Comment by Thatsmusic99** [comment]
Doesn't look like the Maven workflow could run, it looks like an easy fix though so feel free to have at it and we should be done. :)

**Review by Thatsmusic99 — APPROVED** [review]
Looks flawless now! Thank you for your valuable contributions to the plugin, especially in its early stages, I greatly appreciate it.

**Pull request merged**
